export const main_to_sub_category_map = {
    "Decoration": ["tissue box", "bowls", "ashtray", "trays", "candle stands",
                   "mirrors", "bath decor", "flowers", "vase", "mix decoration items",
                   "photo frame & album decor", "jewellery box"],
    "Toys": ["video games", "educational toys", "activity toys"] ,
    "Grocery": ["dairy", "pantry", "beverages", "frozen food", "deli", "general items",
                "snacks", "home baking", "diet and nutrition", "fruits & vegetables"],
    "Health and Beauty": ["toiletries", "hair care", "personal care", "skin care", "cosmetic", "perfume"],
    "Household Essentials": ["insecticides", "kitchen ware", "laundry", "cleaners", "kitchen items",
                             "electric goods", "plastic & paper goods", "home goods", "car care"],
    "Baby Care": ["baby products", "baby feeding", "diapers"],
    "Pet Food": ["dog food", "feed", "cat food",],
    'Miscellaneous': ['other'],
    "Men's Clothing": ["mens", "boys"],
    "Women's Clothing": ["unstitched", "stitched", "bottoms", "girls", "tops", "dresses", "stitched/unstitched"],
    "Accessories": ["bags", "shawls/stoles", "socks", "undergarments", "other accessories"],
}

export const sub_catagories = {
    "mcc":[
        "Baby Products",
        "General Items",
        "Other",
        "Snacks",
        "Beverages",
        "Dairy",
        "Fruits & Vegetables",
        "Cosmetic",
        "Cat Food",
        "Toiletries",
        "Diapers",
        "Perfume",
        "Deli",
        "Laundry",
        "Skin Care",
        "Mens",
        "Decoration",
        "Flowers",
        "Diet And Nutrition",
        "Home Baking",
        "Dog Food",
        "Vase",
        "Photo Frame & Album Decor",
        "Electronics",
        "Juicer Blender & Grinder",
        "Tissue Box",
        "Other Electronics",
        "Baby Feeding"
    ],
    "alfatah":[
        "Beverages",
        "Frozen Food",
        "General Items",
        "Other",
        "Deli",
        "Snacks",
        "Diet And Nutrition",
        "Diapers",
        "Baby Feeding",
        "Dog Food",
        "Baby Products",
        "Hair Care",
        "Cat Food",
        "Toiletries",
        "Perfume",
        "Decoration",
        "Vase",
        "Fruits & Vegetables",
        "Car Care",
        "Home Goods",
        "Plastic & Paper Goods",
        "Electric Goods",
        "Cleaners",
        "Laundry",
        "Flowers",
        "Insecticides",
        "Kitchen Ware",
        "Skin Care",
        "Personal Care",
        "Home Baking",
        "Dairy",
        "Pantry",
        "Cosmetic",
        "Electronics",
        "Juicer Blender & Grinder",
        "Activity Toys",
    ],
    "gulahmed":[
        "Tops",
        "Bottoms",
        "Stitched",
        "Mens",
        "Other",
        "Unstitched",
        "Undergarments",
        "Bags",
        "Footwear",
        "Stitched/Unstitched"
    ],
    "khaadi":[
        "Stitched",
        "Other",
        "Socks",
        "Tops",
        "Bottoms",
        "Undergarments",
        "Dresses",
        "Boys",
    ],
    "metro":[
        "Other",
        "Fruits & Vegetables",
        "Cleaners",
        "Toiletries",
        "General Items",
        "Dairy",
        "Laundry",
        "Diapers",
        "Insecticides",
        "Hair Care",
        "Electronics",
        "Other Electronics",
        "Perfume",
        "Beverages",
        "Snacks",
        "Home Baking",
        "Frozen Food"
    ],
    "sanasafinaz":[
        "Unstitched",
        "Other",
        "Bottoms",
        "Stitched/Unstitched"
    ],
    "warda":[
        "Stitched",
        "Tops",
        "Other",
        "Stitched/Unstitched",
        "Bottoms",
        "Unstitched"
    ],
    "J.":[
        "Boys",
        "Other",
        "Stitched",
        "Tops",
        "Bottoms",
        "Unstitched",
        "Footwear",
        "Undergarments",
        "Stitched/Unstitched",
        "Bags"
    ]
}

export const clothing_category_map = {
    "Men's Clothing": ["mens", "boys"],
    "Women's Clothing": ["unstitched", "stitched", "bottoms", "girls", "tops", "dresses", "stitched/unstitched"],
    "Accessories": ["bags", "shawls/stoles", "socks", "undergarments", "other accessories"],
}
export const groxer_category_map = {
    "Accessories": ["other accessories"],
    "Decoration": ["tissue box", "bowls", "ashtray", "trays", "candle stands",
                   "mirrors", "bath decor", "flowers", "vase", "mix decoration items",
                   "photo frame & album decor", "jewellery box"],
    "Toys": ["video games", "educational toys", "activity toys"] ,
    "Grocery": ["dairy", "pantry", "beverages", "frozen food", "deli", "general items",
                "snacks", "home baking", "diet and nutrition", "fruits & vegetables"],
    "Health and Beauty": ["toiletries", "hair care", "personal care", "skin care", "cosmetic", "perfume"],
    "Household Essentials": ["insecticides", "kitchen ware", "laundry", "cleaners", "kitchen items",
                             "electric goods", "plastic & paper goods", "home goods", "car care"],
    "Baby Care": ["baby products", "baby feeding", "diapers"],
    "Pet Food": ["dog food", "feed", "cat food",],
}