export const main_to_sub_category_map = {
    'Electronics': ['hair accessories', 'juicer blender & grinder', 'irons', 'shavers & trimmers',
                    'kettles & coffee makers', 'vacuum cleaners', 'fryers', 'fans', 'e mixer',
                    'toaster & sandwich maker', 'insect killers', 'medical accessories',
                    'scales', 'humidifier', 'choppers', 'emergency lights', 'bbq grills'],
    "Men's Clothing": ['mens'],
    "Women's Clothing": ['unstitched', 'stitched', 'bottoms', 'girls', 'tops', 'dresses'],
    'Accessories': ['bags', 'shawls/stoles', 'socks', 'undergarments', 'other accessories'],
    'Decoration': ['tissue box', 'bowls', 'ashtray', 'trays', 'candle stands',
                   'mirrors', 'bath decor', 'flowers', 'vase', 'mix decoration items',
                   'photo frame & album decor', 'jewellery box'],
    'Toys': ['video games', 'educational toys', 'activity toys'] ,
    'Grocery': ['dairy', 'pantry', 'beverages', 'frozen food', 'deli',
                'snacks', 'home baking', 'diet and nutrition', 'fruits & vegetables'],
    'Health and Beauty': ['toiletries', 'hair care', 'personal care', 'skin care', 'cosmetic', 'perfume'],
    'Household Essentials': ['insecticides', 'kitchen ware', 'laundry', 'cleaners', 'kitchen items',
                             'electric goods', 'plastic & paper goods', 'home goods', 'car care'],
    'Baby Care': ['baby products', 'baby feeding', 'diapers'],
    'Pet Food': ['dog food', 'feed', 'cat food',],
    'Miscellaneous': ['other']
}